/*
 * Create Commitment
 * This is Swagger UI environment generated for the TMF Agreement Management specification
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.example.demo.model.eai;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.springframework.validation.annotation.Validated;

import java.util.ArrayList;
import java.util.List;

/**
 * An agreement represents a contract or arrangement, either written or verbal and sometimes enforceable by law, such as a service level agreement or a customer price agreement. An agreement involves a number of other business entities, such as products, services, and resources and/or their specifications. Skipped properties: id,href
 */
@Validated
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2022-08-22T11:43:31.605Z")
public class AgreementCreate {
  public AgreementCreate(String agreementType, String description, Integer documentNumber, String initialDate, String name, String statementOfIntent, String status, String version, List<AgreementAuthorization> agreementAuthorization, List<AgreementItem> agreementItem, TimePeriod agreementPeriod, AgreementSpecificationRef agreementSpecification, List<AgreementRef> associatedAgreement, List<Characteristic> characteristic, TimePeriod completionDate, List<RelatedParty> engagedParty, String baseType, String schemaLocation, String type) {
    this.agreementType = agreementType;
    this.description = description;
    this.documentNumber = documentNumber;
    this.initialDate = initialDate;
    this.name = name;
    this.statementOfIntent = statementOfIntent;
    this.status = status;
    this.version = version;
    this.agreementAuthorization = agreementAuthorization;
    this.agreementItem = agreementItem;
    this.agreementPeriod = agreementPeriod;
    this.agreementSpecification = agreementSpecification;
    this.associatedAgreement = associatedAgreement;
    this.characteristic = characteristic;
    this.completionDate = completionDate;
    this.engagedParty = engagedParty;
    this.baseType = baseType;
    this.schemaLocation = schemaLocation;
    this.type = type;
  }

  @JsonProperty("agreementType")
  private String agreementType = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("documentNumber")
  private Integer documentNumber = null;

  @JsonProperty("initialDate")
  private String initialDate = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("statementOfIntent")
  private String statementOfIntent = null;

  @JsonProperty("status")
  private String status = null;

  @JsonProperty("version")
  private String version = null;

  @JsonProperty("agreementAuthorization")
  private List<AgreementAuthorization> agreementAuthorization = null;

  @JsonProperty("agreementItem")
  private List<AgreementItem> agreementItem = new ArrayList<AgreementItem>();

  @JsonProperty("agreementPeriod")
  private TimePeriod agreementPeriod = null;

  @JsonProperty("agreementSpecification")
  private AgreementSpecificationRef agreementSpecification = null;

  @JsonProperty("associatedAgreement")
  private List<AgreementRef> associatedAgreement = null;

  @JsonProperty("characteristic")
  private List<Characteristic> characteristic = null;

  @JsonProperty("completionDate")
  private TimePeriod completionDate = null;

  @JsonProperty("engagedParty")
  private List<RelatedParty> engagedParty = new ArrayList<RelatedParty>();

  @JsonProperty("@baseType")
  private String baseType = null;

  @JsonProperty("@schemaLocation")
  private String schemaLocation = null;

  @JsonProperty("@type")
  private String type = null;

  public String getAgreementType() {
    return agreementType;
  }

  public void setAgreementType(String agreementType) {
    this.agreementType = agreementType;
  }

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Integer getDocumentNumber() {
    return documentNumber;
  }

  public void setDocumentNumber(Integer documentNumber) {
    this.documentNumber = documentNumber;
  }

  public String getInitialDate() {
    return initialDate;
  }

  public void setInitialDate(String initialDate) {
    this.initialDate = initialDate;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getStatementOfIntent() {
    return statementOfIntent;
  }

  public void setStatementOfIntent(String statementOfIntent) {
    this.statementOfIntent = statementOfIntent;
  }

  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public List<AgreementAuthorization> getAgreementAuthorization() {
    return agreementAuthorization;
  }

  public void setAgreementAuthorization(List<AgreementAuthorization> agreementAuthorization) {
    this.agreementAuthorization = agreementAuthorization;
  }

  public List<AgreementItem> getAgreementItem() {
    return agreementItem;
  }

  public void setAgreementItem(List<AgreementItem> agreementItem) {
    this.agreementItem = agreementItem;
  }

  public TimePeriod getAgreementPeriod() {
    return agreementPeriod;
  }

  public void setAgreementPeriod(TimePeriod agreementPeriod) {
    this.agreementPeriod = agreementPeriod;
  }

  public AgreementSpecificationRef getAgreementSpecification() {
    return agreementSpecification;
  }

  public void setAgreementSpecification(AgreementSpecificationRef agreementSpecification) {
    this.agreementSpecification = agreementSpecification;
  }

  public List<AgreementRef> getAssociatedAgreement() {
    return associatedAgreement;
  }

  public void setAssociatedAgreement(List<AgreementRef> associatedAgreement) {
    this.associatedAgreement = associatedAgreement;
  }

  public List<Characteristic> getCharacteristic() {
    return characteristic;
  }

  public void setCharacteristic(List<Characteristic> characteristic) {
    this.characteristic = characteristic;
  }

  public TimePeriod getCompletionDate() {
    return completionDate;
  }

  public void setCompletionDate(TimePeriod completionDate) {
    this.completionDate = completionDate;
  }

  public List<RelatedParty> getEngagedParty() {
    return engagedParty;
  }

  public void setEngagedParty(List<RelatedParty> engagedParty) {
    this.engagedParty = engagedParty;
  }

  public String getBaseType() {
    return baseType;
  }

  public void setBaseType(String baseType) {
    this.baseType = baseType;
  }

  public String getSchemaLocation() {
    return schemaLocation;
  }

  public void setSchemaLocation(String schemaLocation) {
    this.schemaLocation = schemaLocation;
  }

  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }
}

