/*
 * Create Commitment
 * This is Swagger UI environment generated for the TMF Agreement Management specification
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.example.demo.model.eai;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.springframework.validation.annotation.Validated;

import java.util.Objects;

/**
 * The event data structure
 */
@Validated
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2022-08-22T11:43:31.605Z")
public class AgreementDeleteEventPayload {
  @JsonProperty("agreement")
  private Agreement agreement = null;

  public AgreementDeleteEventPayload agreement(Agreement agreement) {
    this.agreement = agreement;
    return this;
  }

   /**
   * The involved resource data for the event
   * @return agreement
  **/
  @ApiModelProperty(value = "The involved resource data for the event")
  public Agreement getAgreement() {
    return agreement;
  }

  public void setAgreement(Agreement agreement) {
    this.agreement = agreement;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgreementDeleteEventPayload agreementDeleteEventPayload = (AgreementDeleteEventPayload) o;
    return Objects.equals(this.agreement, agreementDeleteEventPayload.agreement);
  }

  @Override
  public int hashCode() {
    return Objects.hash(agreement);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgreementDeleteEventPayload {\n");
    
    sb.append("    agreement: ").append(toIndentedString(agreement)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

